spring:
  application:
    name: shopapp
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DRIVER_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASS}
  liquibase:
    enable: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  jpa:
    properties:
      hibernate.dialect: ${DIALECT}
      show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: @spring.profiles.active@
server:
  port: ${PORT}
  servlet:
    context-path: /api/v1
